// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:519346109803:web:ac06582ded29f1c88c202e',
    messagingSenderId: '519346109803',
    projectId: 'movie-recommendation-sys-21b5d',
    authDomain: 'movie-recommendation-sys-21b5d.firebaseapp.com',
    storageBucket: 'movie-recommendation-sys-21b5d.firebasestorage.app',
    measurementId: 'G-FGBF2J3SQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '<FIREBASE_API_KEY_PLACEHOLDER>',
    appId: '1:519346109803:android:571ebca38f49e2eb8c202e',
    messagingSenderId: '519346109803',
    projectId: 'movie-recommendation-sys-21b5d',
    storageBucket: 'movie-recommendation-sys-21b5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '<FIREBASE_API_KEY_PLACEHOLDER>',
    appId: '1:519346109803:ios:68d03e1f293ea7118c202e',
    messagingSenderId: '519346109803',
    projectId: 'movie-recommendation-sys-21b5d',
    storageBucket: 'movie-recommendation-sys-21b5d.firebasestorage.app',
    iosClientId: '519346109803-ajh8f0l29l3t067rceegqkne7pvcg9ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieRecommendApp',
  );
}
